### ISSUE TITLE
Cannot fine Module Discord.Js

### ISSUE THREAD

**Issue by prolexgreen** [reaganmcf/discord-stock-bot#13]
Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/Users/coolb/Desktop/discord-stock-bot-master/discord-stock-bot/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Running with with ubuntu 20.04.1

**Comment by prolexgreen** [comment]
Nvm fixed the issue by rebuilding node js.
